export const HEADER_HEIGHT = 60
// export const BANNER_RATIO = 80 / 29
// export const MAX_INPUT_LENGTH = 254
// export const RUPEES = '\u20B9'
// export const SHIMMER_SPEED = 10
// export const COLOR_DISABLED = "#eeeeee"
// export const BORDER_RADIUS = 10
// export const HOME_DIVIDER_MARGIN = 5
// export const ITEMS_FOUND = "Items found"